# Generated by Django 5.0.3 on 2024-04-03 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfnl', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
        migrations.AddField(
            model_name='product',
            name='last_modified',
            field=models.DateField(default=datetime.datetime(2024, 4, 3, 8, 50, 54, 649509, tzinfo=datetime.timezone.utc), verbose_name='Dernière modification'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='typeproduct',
            name='unit',
            field=models.CharField(default='kilo', max_length=20, verbose_name='Unité'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='coop_name',
            field=models.CharField(max_length=50, verbose_name='Nom de la coopérative'),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='coop_phone',
            field=models.CharField(max_length=13, verbose_name='Numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_name',
            field=models.CharField(max_length=50, verbose_name='Nom du membre'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_phone',
            field=models.CharField(max_length=13, verbose_name='Numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='typeproduct',
            name='type_product_name',
            field=models.CharField(max_length=50, verbose_name='Type de produit'),
        ),
    ]
