# Generated by Django 5.0.3 on 2024-04-04 08:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfnl', '0002_remove_product_unit_product_last_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(max_length=10),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='offered_product_1',
            field=models.CharField(choices=[('AK', 'Amande de karité'), ('BK', 'Beurre de karité'), ('SO', 'Soumabala'), ('BS', 'Biscuit de pain de singe'), ('JS', 'Jus de pain de singe'), ('SN', 'Savon de neem'), ('HN', 'Huile de neem')], default='BK', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cooperative',
            name='offered_product_2',
            field=models.CharField(choices=[('AK', 'Amande de karité'), ('BK', 'Beurre de karité'), ('SO', 'Soumabala'), ('BS', 'Biscuit de pain de singe'), ('JS', 'Jus de pain de singe'), ('SN', 'Savon de neem'), ('HN', 'Huile de neem')], default='AK', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cooperative',
            name='offered_product_3',
            field=models.CharField(choices=[('AK', 'Amande de karité'), ('BK', 'Beurre de karité'), ('SO', 'Soumabala'), ('BS', 'Biscuit de pain de singe'), ('JS', 'Jus de pain de singe'), ('SN', 'Savon de neem'), ('HN', 'Huile de neem')], default='JS', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='coop_phone',
            field=models.CharField(max_length=14, verbose_name='Numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_phone',
            field=models.CharField(max_length=14, verbose_name='Numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_modified',
            field=models.DateField(default=datetime.datetime(2024, 4, 4, 8, 47, 46, 102092, tzinfo=datetime.timezone.utc), verbose_name='Dernière modification'),
        ),
        migrations.DeleteModel(
            name='TypeProduct',
        ),
    ]
