# Generated by Django 5.0.3 on 2024-04-04 09:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfnl', '0003_alter_product_type_cooperative_offered_product_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperative',
            name='offered_product_1',
            field=models.CharField(choices=[('AK', 'Amande de karité'), ('BK', 'Beurre de karité'), ('SO', 'Soumabala'), ('BS', 'Biscuit de pain de singe'), ('JS', 'Jus de pain de singe'), ('SN', 'Savon de neem'), ('HN', 'Huile de neem')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='offered_product_2',
            field=models.CharField(choices=[('AK', 'Amande de karité'), ('BK', 'Beurre de karité'), ('SO', 'Soumabala'), ('BS', 'Biscuit de pain de singe'), ('JS', 'Jus de pain de singe'), ('SN', 'Savon de neem'), ('HN', 'Huile de neem')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='offered_product_3',
            field=models.CharField(choices=[('AK', 'Amande de karité'), ('BK', 'Beurre de karité'), ('SO', 'Soumabala'), ('BS', 'Biscuit de pain de singe'), ('JS', 'Jus de pain de singe'), ('SN', 'Savon de neem'), ('HN', 'Huile de neem')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_modified',
            field=models.DateField(default=datetime.datetime(2024, 4, 4, 9, 36, 19, 964010, tzinfo=datetime.timezone.utc), verbose_name='Dernière modification'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(editable=False, max_length=10),
        ),
    ]
