# Generated by Django 5.0.3 on 2024-04-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfnl', '0005_alter_cooperative_offered_product_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='last_modified',
            field=models.DateField(auto_now_add=True, verbose_name='Dernière modification'),
        ),
    ]
