# Generated by Django 5.0.3 on 2024-04-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfnl', '0006_alter_product_last_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
        migrations.AddField(
            model_name='product',
            name='prod_type',
            field=models.CharField(default='None', editable=False, max_length=10, verbose_name='Type de produit'),
            preserve_default=False,
        ),
    ]
