# Generated by Django 5.0.3 on 2024-04-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfnl', '0009_cooperative_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_type',
            field=models.CharField(max_length=10, verbose_name='Type de produit'),
        ),
    ]
