# Generated by Django 5.0.3 on 2024-04-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfnl', '0010_alter_product_prod_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='telegram_id',
            field=models.IntegerField(default=0, max_length=20, verbose_name='ID telegram'),
            preserve_default=False,
        ),
    ]
