# Generated by Django 5.0.3 on 2024-06-07 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pfnl", "0008_alter_cooperative_offered_product_1_and_more"),
        ("pfnl", "0015_artemisiaseller_alter_cooperative_offered_product_3_and_more"),
    ]

    operations = []
