# Generated by Django 5.0.3 on 2024-06-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telegram_id",
                    models.IntegerField(
                        default=0, unique=True, verbose_name="ID telegram"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        default="None", max_length=20, verbose_name="State"
                    ),
                ),
                (
                    "time_set",
                    models.DateField(auto_now_add=True, verbose_name="Time set"),
                ),
                ("product", models.CharField(max_length=50, verbose_name="Product")),
                ("quantity", models.IntegerField(default=0, verbose_name="Quantity")),
                ("price", models.IntegerField(default=0, verbose_name="Price")),
            ],
        ),
    ]
