# Generated by Django 5.0.3 on 2024-06-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="state",
            name="time_set",
            field=models.DateTimeField(auto_now=True, verbose_name="Time set"),
        ),
    ]
